@startuml
setnamespaceSeparator /
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
hide circle
hide methods
hide stereotypes

'========================
' Model Layer
'========================
package it.univaq/gymportal/model {
  class Course {
    - long id
    - String name
    - String description
    - String code
    - long gym_id
    - java.util.List<FeedbackCourse> feedbackCourse
    - java.util.List<FavoriteCourse> favoriteCourse
  }

  class FavoriteCourse {
    - long id
    - long user_id
    - long course_id
  }

  class FavoriteGym {
    - long id
    - long user
    - long gym_id
  }

  class FeedbackCourse {
    - long id
    - String feed
    - int rating
    - long user_id
    - String userName
    - String userLastname
    - long course
    - String courseName
  }

  class FeedbackGym {
    - long id
    - String feed
    - int rating
    - long user_id
    - String userName
    - String userLastname
    - long gym_id
    - String gymName
  }

  class Gym {
    - long id
    - String name
    - String address
    - String province
    - String region
    - long user_id
    - java.util.List<FeedbackGym> feedbackGym
    - java.util.List<FavoriteGym> favoriteGym
    - java.util.List<Course> course
  }

  class Role {
    - long id
    - String role
  }

  class User {
    - long id
    - String username
    - String email
    - String password
    - String name
    - String lastname
    - java.util.List<FeedbackCourse> feedbackCourse
    - java.util.List<FavoriteGym> favoriteGym
    - java.util.List<FavoriteCourse> favoriteCourse
    - java.util.List<FeedbackGym> feedbackGym
    - java.util.Set<Role> roles
    - java.util.List<Gym> gyms
  }
}

'========================
' Business Layer (Interfaces)
'========================
package it.univaq/gymportal/business {
  abstract class Service {
    # static String urlDB
    # static String userDB
    # static String pswDB
    + void printRS(java.sql.ResultSet)
  }

  interface CourseService {
    + java.util.List<it.univaq.gymportal.model.Course> getCoursesByGym(long gymId) throws it.univaq.gymportal.exceptions.ServiceException
    + java.util.List<it.univaq.gymportal.model.Course> getCoursesByName(long gymId, String hint) throws it.univaq.gymportal.exceptions.ServiceException
    + it.univaq.gymportal.model.Course getCourse(long id) throws it.univaq.gymportal.exceptions.ServiceException
    + long createCourse(it.univaq.gymportal.model.Course course) throws it.univaq.gymportal.exceptions.ServiceException
    + void updateCourse(it.univaq.gymportal.model.Course course) throws it.univaq.gymportal.exceptions.ServiceException
    + void deleteCourse(long id) throws it.univaq.gymportal.exceptions.ServiceException
  }

  interface FavoriteCourseService {
    + long createFavoriteCourse(it.univaq.gymportal.model.FavoriteCourse favoriteCourse) throws it.univaq.gymportal.exceptions.ServiceException
    + java.util.List<it.univaq.gymportal.model.Course> getAllFavoriteCourse(long idUser) throws it.univaq.gymportal.exceptions.ServiceException
    + void deleteFavoriteCourse(long idUser, long idCourse) throws it.univaq.gymportal.exceptions.ServiceException
  }

  interface FavoriteGymService {
    + long createFavoriteGym(it.univaq.gymportal.model.FavoriteGym favoriteGym) throws it.univaq.gymportal.exceptions.ServiceException
    + java.util.List<it.univaq.gymportal.model.Gym> getAllFavoriteGym(long idUser) throws it.univaq.gymportal.exceptions.ServiceException
    + void deleteFavoriteGym(long idUser, long idGym) throws it.univaq.gymportal.exceptions.ServiceException
  }

  interface FeedbackCourseService {
    + long createFeedbackCourse(it.univaq.gymportal.model.FeedbackCourse feedbackCourse) throws it.univaq.gymportal.exceptions.ServiceException
    + it.univaq.gymportal.model.FeedbackCourse getFeedback(long id) throws it.univaq.gymportal.exceptions.ServiceException
    + java.util.List<it.univaq.gymportal.model.FeedbackCourse> getAllFeedbackByCourse(long id) throws it.univaq.gymportal.exceptions.ServiceException
    + java.util.List<it.univaq.gymportal.model.FeedbackCourse> getAllFeedbackByUser(long id) throws it.univaq.gymportal.exceptions.ServiceException
    + void deleteFeedbackCourse(long id) throws it.univaq.gymportal.exceptions.ServiceException
    + void updateFeedbackCourse(it.univaq.gymportal.model.FeedbackCourse feedbackCourse) throws it.univaq.gymportal.exceptions.ServiceException
  }

  interface FeedbackGymService {
    + long createFeedbackGym(it.univaq.gymportal.model.FeedbackGym feedbackGym) throws it.univaq.gymportal.exceptions.ServiceException
    + it.univaq.gymportal.model.FeedbackGym getFeedback(long id) throws it.univaq.gymportal.exceptions.ServiceException
    + java.util.List<it.univaq.gymportal.model.FeedbackGym> getAllFeedbackByGym(long id) throws it.univaq.gymportal.exceptions.ServiceException
    + java.util.List<it.univaq.gymportal.model.FeedbackGym> getAllFeedbackByUser(long id) throws it.univaq.gymportal.exceptions.ServiceException
    + void deleteFeedbackGym(long id) throws it.univaq.gymportal.exceptions.ServiceException
    + void updateFeedbackGym(it.univaq.gymportal.model.FeedbackGym feedbackGym) throws it.univaq.gymportal.exceptions.ServiceException
  }

  interface GymService {
    + java.util.List<it.univaq.gymportal.model.Gym> getAllGyms() throws it.univaq.gymportal.exceptions.ServiceException
    + java.util.List<it.univaq.gymportal.model.Gym> getGymsByRegion(String region) throws it.univaq.gymportal.exceptions.ServiceException
    + java.util.List<it.univaq.gymportal.model.Gym> getGymsByName(String hint) throws it.univaq.gymportal.exceptions.ServiceException
    + it.univaq.gymportal.model.Gym getGym(long id) throws it.univaq.gymportal.exceptions.ServiceException
    + it.univaq.gymportal.model.Gym getGymWithManager(long id) throws it.univaq.gymportal.exceptions.ServiceException
    + long createGym(it.univaq.gymportal.model.Gym gym) throws it.univaq.gymportal.exceptions.ServiceException
    + void updateGym(it.univaq.gymportal.model.Gym gym) throws it.univaq.gymportal.exceptions.ServiceException
    + void deleteGym(long id) throws it.univaq.gymportal.exceptions.ServiceException
  }

  interface UserService {
    + boolean checkUser(String username, String password) throws it.univaq.gymportal.exceptions.ServiceException
    + boolean checkRole(String username, String role) throws it.univaq.gymportal.exceptions.ServiceException
    + it.univaq.gymportal.model.User getUserById(long id) throws it.univaq.gymportal.exceptions.ServiceException
    + it.univaq.gymportal.model.User getUserByIdWithoutPassword(long id) throws it.univaq.gymportal.exceptions.ServiceException
    + it.univaq.gymportal.model.User getUserByUsername(String username) throws it.univaq.gymportal.exceptions.ServiceException
    + long createUser(it.univaq.gymportal.model.User user) throws it.univaq.gymportal.exceptions.ServiceException
    + void addRoleToUser(long idUser) throws it.univaq.gymportal.exceptions.ServiceException
    + void deleteUser(long id) throws it.univaq.gymportal.exceptions.ServiceException
    + void updateUser(it.univaq.gymportal.model.User user) throws it.univaq.gymportal.exceptions.ServiceException
  }
}

'========================
' Business Layer (Implementations)
'========================
package it.univaq/gymportal/business/impl {
  class CourseServiceImpl
  class FavoriteCourseServiceImpl
  class FavoriteGymServiceImpl
  class FeedbackCourseServiceImpl
  class FeedbackGymServiceImpl
  class GymServiceImpl
  class UserServiceImpl
}

it.univaq/gymportal/business/impl/CourseServiceImpl -|> it.univaq/gymportal/business/CourseService
it.univaq/gymportal/business/impl/FavoriteCourseServiceImpl -|> it.univaq/gymportal/business/FavoriteCourseService
it.univaq/gymportal/business/impl/FavoriteGymServiceImpl -|> it.univaq/gymportal/business/FavoriteGymService
it.univaq/gymportal/business/impl/FeedbackCourseServiceImpl -|> it.univaq/gymportal/business/FeedbackCourseService
it.univaq/gymportal/business/impl/FeedbackGymServiceImpl -|> it.univaq/gymportal/business/FeedbackGymService
it.univaq/gymportal/business/impl/GymServiceImpl -|> it.univaq/gymportal/business/GymService
it.univaq/gymportal/business/impl/UserServiceImpl -|> it.univaq/gymportal/business/UserService

it.univaq/gymportal/business/impl/CourseServiceImpl --|> it.univaq/gymportal/business/Service
it.univaq/gymportal/business/impl/FavoriteCourseServiceImpl --|> it.univaq/gymportal/business/Service
it.univaq/gymportal/business/impl/FavoriteGymServiceImpl --|> it.univaq/gymportal/business/Service
it.univaq/gymportal/business/impl/FeedbackCourseServiceImpl --|> it.univaq/gymportal/business/Service
it.univaq/gymportal/business/impl/FeedbackGymServiceImpl --|> it.univaq/gymportal/business/Service
it.univaq/gymportal/business/impl/GymServiceImpl --|> it.univaq/gymportal/business/Service
it.univaq/gymportal/business/impl/UserServiceImpl --|> it.univaq/gymportal/business/Service

'========================
' Exceptions
'========================
package it.univaq/gymportal/exceptions {
  class ErrorMessage {
    - int code
    - String message
  }

  class ServiceException {
    - int sqlErrorCode
  }

  class ServiceExceptionMapper
}

it.univaq/gymportal/exceptions/ServiceException --|> java/lang/Exception
it.univaq/gymportal/exceptions/ServiceExceptionMapper ..> it.univaq/gymportal/exceptions/ServiceException
it.univaq/gymportal/exceptions/ServiceExceptionMapper ..> it.univaq/gymportal/exceptions/ErrorMessage

'========================
' REST Resources
'========================
package it.univaq/gymportal/resources/rest {
  class AuthRes
  class CourseRes {
    - long idGym
  }
  class FavoriteRes {
    - long user_id
  }
  class FeedbackCourseRes {
    - long idCourse
  }
  class FeedbackGymRes {
    - long idGym
  }
  class GymRes
  class UserRes
}

' Resource -> Service implementation dependencies (as coded)
it.univaq/gymportal/resources/rest/AuthRes ..> it.univaq/gymportal/business/impl/UserServiceImpl
it.univaq/gymportal/resources/rest/GymRes ..> it.univaq/gymportal/business/impl/GymServiceImpl
it.univaq/gymportal/resources/rest/GymRes ..> it.univaq/gymportal/business/impl/UserServiceImpl
it.univaq/gymportal/resources/rest/CourseRes ..> it.univaq/gymportal/business/impl/CourseServiceImpl
it.univaq/gymportal/resources/rest/CourseRes ..> it.univaq/gymportal/business/impl/UserServiceImpl
it.univaq/gymportal/resources/rest/CourseRes ..> it.univaq/gymportal/business/impl/GymServiceImpl
it.univaq/gymportal/resources/rest/FeedbackCourseRes ..> it.univaq/gymportal/business/impl/FeedbackCourseServiceImpl
it.univaq/gymportal/resources/rest/FeedbackCourseRes ..> it.univaq/gymportal/business/impl/UserServiceImpl
it.univaq/gymportal/resources/rest/FeedbackGymRes ..> it.univaq/gymportal/business/impl/FeedbackGymServiceImpl
it.univaq/gymportal/resources/rest/FeedbackGymRes ..> it.univaq/gymportal/business/impl/UserServiceImpl
it.univaq/gymportal/resources/rest/FavoriteRes ..> it.univaq/gymportal/business/impl/FavoriteGymServiceImpl
it.univaq/gymportal/resources/rest/FavoriteRes ..> it.univaq/gymportal/business/impl/FavoriteCourseServiceImpl
it.univaq/gymportal/resources/rest/FavoriteRes ..> it.univaq/gymportal/business/impl/UserServiceImpl
it.univaq/gymportal/resources/rest/UserRes ..> it.univaq/gymportal/business/impl/UserServiceImpl
it.univaq/gymportal/resources/rest/UserRes ..> it.univaq/gymportal/business/impl/FeedbackGymServiceImpl
it.univaq/gymportal/resources/rest/UserRes ..> it.univaq/gymportal/business/impl/FeedbackCourseServiceImpl

' Sub-resource factory relations
it.univaq/gymportal/resources/rest/GymRes ..> it.univaq/gymportal/resources/rest/CourseRes
it.univaq/gymportal/resources/rest/GymRes ..> it.univaq/gymportal/resources/rest/FeedbackGymRes
it.univaq/gymportal/resources/rest/CourseRes ..> it.univaq/gymportal/resources/rest/FeedbackCourseRes
it.univaq/gymportal/resources/rest/UserRes ..> it.univaq/gymportal/resources/rest/FavoriteRes

'========================
' Model Aggregations
'========================
it.univaq/gymportal/model/Gym o-- "0..*" it.univaq/gymportal/model/Course
it.univaq/gymportal/model/Gym o-- "0..*" it.univaq/gymportal/model/FeedbackGym
it.univaq/gymportal/model/Gym o-- "0..*" it.univaq/gymportal/model/FavoriteGym

it.univaq/gymportal/model/Course o-- "0..*" it.univaq/gymportal/model/FeedbackCourse
it.univaq/gymportal/model/Course o-- "0..*" it.univaq/gymportal/model/FavoriteCourse

it.univaq/gymportal/model/User o-- "0..*" it.univaq/gymportal/model/FavoriteGym
it.univaq/gymportal/model/User o-- "0..*" it.univaq/gymportal/model/FavoriteCourse
it.univaq/gymportal/model/User o-- "0..*" it.univaq/gymportal/model/FeedbackGym
it.univaq/gymportal/model/User o-- "0..*" it.univaq/gymportal/model/FeedbackCourse
it.univaq/gymportal/model/User o-- "0..*" it.univaq/gymportal/model/Role
it.univaq/gymportal/model/User o-- "0..*" it.univaq/gymportal/model/Gym

'========================
' Runner
'========================
class it.univaq/gymportal/GympotalWSEndpoint

@enduml