@startuml 


package "treeco.dialects.trunk" {
  class AggregateLeafOp <<IRDLOperation>> {
    +ensemble: TreeEnsembleType
    +tree: TreeType
    +leaf: TensorType
    +tensor_out: TensorType
    +res: TensorType
  }
  class GetTreeDepthOp <<IRDLOperation>> { }
  class GetLeafValueOp <<IRDLOperation>> {
    +tree: TreeType
    +leaf: LeafType
    +res: TensorType
  }
  class GetLeafOp <<IRDLOperation>> {
    +tree: TreeType
    +node: NodeType
    +res: LeafType
  }
  class VisitNextNodeOp <<IRDLOperation>> {
    +tree: TreeType
    +node: NodeType
    +data_in: TensorType
    +result: NodeType
    +root_node?: NodeType
  }
  class IsLeafOp <<IRDLOperation>> {
    +tree: TreeType
    +node: NodeType
    +result: Bool
  }
  class IsLeafConditionOp <<IRDLOperation>> { }
  class GetRootOp <<IRDLOperation>> {
    +ensemble: TreeEnsembleType
    +tree: TreeType
    +result: NodeType
  }
  class TreeEnsembleConstantOp <<IRDLOperation>> {
    +ensemble: TreeEnsembleAttr
    +result: TreeEnsembleType
  }
  class PostTransform <<IRDLOperation>> { +mode: StringAttr }
  class GetTreeOp <<IRDLOperation>> {
    +tree_ensemble: TreeEnsembleType
    +tree_index: IndexType
    +result: TreeType
  }
  class TraverseTreeOp <<IRDLOperation>> {
    +tree: TreeType
    +data_in: MemRefType
    +result: LeafType
  }

  AggregateLeafOp ..> treeco.dialects.treeco.TreeEnsembleType
  AggregateLeafOp ..> treeco.dialects.treeco.TreeType
  AggregateLeafOp ..> treeco.dialects.treeco.LeafType
  GetLeafValueOp ..> treeco.dialects.treeco.TreeType
  GetLeafValueOp ..> treeco.dialects.treeco.LeafType
  GetLeafOp ..> treeco.dialects.treeco.TreeType
  GetLeafOp ..> treeco.dialects.treeco.NodeType
  VisitNextNodeOp ..> treeco.dialects.treeco.TreeType
  VisitNextNodeOp ..> treeco.dialects.treeco.NodeType
  IsLeafOp ..> treeco.dialects.treeco.TreeType
  IsLeafOp ..> treeco.dialects.treeco.NodeType
  GetRootOp ..> treeco.dialects.treeco.TreeEnsembleType
  GetRootOp ..> treeco.dialects.treeco.TreeType
  TreeEnsembleConstantOp ..> treeco.dialects.treeco.TreeEnsembleAttr
  TreeEnsembleConstantOp ..> treeco.dialects.treeco.TreeEnsembleType
  GetTreeOp ..> treeco.dialects.treeco.TreeEnsembleType
  GetTreeOp ..> treeco.dialects.treeco.TreeType
  TraverseTreeOp ..> treeco.dialects.treeco.TreeType
  TraverseTreeOp ..> treeco.dialects.treeco.LeafType
}

@enduml